'use client'

import { useEffect, useState, useCallback, useRef } from 'react'
import { StatsBar } from '@/components/dashboard/StatsBar'
import { EventFeed } from '@/components/dashboard/EventFeed'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import type { EventCluster, GeneratedPost } from '@/types'

export type ClusterWithPosts = EventCluster & { posts?: GeneratedPost[] }

export default function DashboardPage() {
  const [clusters, setClusters] = useState<ClusterWithPosts[]>([])
  const [loading, setLoading] = useState(true)
  const [fetching, setFetching] = useState(false)
  const [fetchResult, setFetchResult] = useState<string | null>(null)
  const [hasHighRisk, setHasHighRisk] = useState(false)
  const [pendingCount, setPendingCount] = useState(0)
  const [postedToday, setPostedToday] = useState(0)
  const [newAlert, setNewAlert] = useState<{ count: number; headline: string } | null>(null)
  const sseRef = useRef<EventSource | null>(null)

  const loadClusters = useCallback(async () => {
    try {
      const res = await fetch('/api/events?include_posts=true')
      const data = await res.json() as { clusters: ClusterWithPosts[] }
      setClusters(data.clusters ?? [])
      setHasHighRisk(data.clusters.some(c => c.riskLevel === 'high' && (c.postCount ?? 0) === 0))
    } catch {}
    setLoading(false)
  }, [])

  const loadStats = useCallback(async () => {
    try {
      const dayStart = Date.now() - 24 * 60 * 60 * 1000
      const [pendingData, postedData] = await Promise.all([
        fetch('/api/posts?status=pending&limit=100').then(r => r.json()),
        fetch('/api/posts?status=posted&limit=100').then(r => r.json()),
      ]) as [{ total: number }, { posts: Array<{ postedAt: number | null }> }]
      setPendingCount(pendingData.total ?? 0)
      const todayPosts = postedData.posts?.filter(p => p.postedAt && p.postedAt > dayStart).length ?? 0
      setPostedToday(todayPosts)
    } catch {}
  }, [])

  // Real-time SSE monitoring
  useEffect(() => {
    const es = new EventSource('/api/events/stream')
    sseRef.current = es

    es.onmessage = (e) => {
      try {
        const data = JSON.parse(e.data) as { type: string; count: number; topHeadline: string }
        if (data.type === 'new_clusters') {
          setNewAlert({ count: data.count, headline: data.topHeadline })
          loadClusters()
          loadStats()
        }
      } catch {}
    }

    return () => { es.close() }
  }, [loadClusters, loadStats])

  useEffect(() => {
    loadClusters()
    loadStats()
    const interval = setInterval(() => { loadClusters(); loadStats() }, 60000)
    return () => clearInterval(interval)
  }, [loadClusters, loadStats])

  const dayStart = Date.now() - 24 * 60 * 60 * 1000
  const eventsToday = clusters.filter(c => c.firstSeenAt > dayStart).length

  async function fetchNews() {
    setFetching(true)
    setFetchResult(null)
    try {
      const res = await fetch('/api/news/fetch', { method: 'POST' })
      const data = await res.json() as { ingested: number; clustered: number; errors: number; autoGenerated: number }
      setFetchResult(`抓取 ${data.ingested} 篇文章，${data.clustered} 个新事件，自动生成 ${data.autoGenerated ?? 0} 个推文${data.errors > 0 ? `，${data.errors} 个来源失败` : ''}`)
      await loadClusters()
      await loadStats()
    } catch {
      setFetchResult('抓取失败，请检查网络')
    } finally {
      setFetching(false)
    }
  }

  async function handleGenerate(clusterId: string) {
    await fetch('/api/posts/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ cluster_id: clusterId }),
    })
    await loadClusters()
    await loadStats()
  }

  async function handleApprove(postId: string) {
    await fetch(`/api/posts/${postId}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'approved', reviewed_by: 'dashboard' }),
    })
    await loadClusters()
    await loadStats()
  }

  async function handleReject(postId: string, reason: string) {
    await fetch(`/api/posts/${postId}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'rejected', rejection_reason: reason, reviewed_by: 'dashboard' }),
    })
    await loadClusters()
    await loadStats()
  }

  async function handleCopyAndPost(postId: string) {
    const res = await fetch(`/api/posts/${postId}/publish`, { method: 'POST' })
    const data = await res.json() as { intentUrl?: string }
    if (data.intentUrl) window.open(data.intentUrl, '_blank')
    await loadClusters()
    await loadStats()
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-6 space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3 pb-4 border-b border-slate-200">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">SignalDesk</h1>
          <p className="text-xs text-slate-500 mt-0.5">实时监控 · 高分自动生成 · 每5分钟刷新</p>
        </div>
        <div className="flex items-center gap-3">
          <a href="/review" className="text-sm font-medium text-slate-600 hover:text-slate-900">审核队列</a>
          <a href="/settings" className="text-sm font-medium text-slate-600 hover:text-slate-900">设置</a>
          <Button size="sm" onClick={fetchNews} disabled={fetching} className="bg-slate-900 text-white hover:bg-slate-700">
            {fetching ? '抓取中…' : '立即抓取新闻'}
          </Button>
        </div>
      </div>

      {/* Real-time new events alert */}
      {newAlert && (
        <Alert className="border-blue-300 bg-blue-50 cursor-pointer" onClick={() => setNewAlert(null)}>
          <AlertDescription className="text-blue-800 text-sm font-medium">
            🔔 {newAlert.count} 条新事件 — 最新：{newAlert.headline.slice(0, 60)}…
            <span className="ml-2 text-xs text-blue-500">(点击关闭)</span>
          </AlertDescription>
        </Alert>
      )}

      {/* High risk alert */}
      {hasHighRisk && (
        <Alert variant="destructive">
          <AlertDescription>⚠️ 存在高风险事件尚未生成推文，请在下方优先处理。</AlertDescription>
        </Alert>
      )}

      {fetchResult && (
        <Alert className="border-green-300 bg-green-50">
          <AlertDescription className="text-green-800 text-sm">{fetchResult}</AlertDescription>
        </Alert>
      )}

      <StatsBar
        eventsToday={eventsToday}
        pendingReview={pendingCount}
        postedToday={postedToday}
        sourcesActive={27}
      />

      <div>
        <h2 className="text-base font-bold text-slate-700 mb-3">事件列表（按评分排序）</h2>
        <EventFeed
          clusters={clusters}
          loading={loading}
          onGenerate={handleGenerate}
          onApprove={handleApprove}
          onReject={handleReject}
          onCopyAndPost={handleCopyAndPost}
        />
      </div>
    </div>
  )
}
