import { NextResponse } from 'next/server'
import { fetchAllSources } from '@/lib/news/fetcher'
import { clusterNewItems } from '@/lib/news/clusterer'
import { generateSmartPosts } from '@/lib/ai/generator'
import { db } from '@/lib/db'
import { eventClusters, settings } from '@/lib/db/schema'
import { eq, and, gt } from 'drizzle-orm'

export async function POST() {
  try {
    const { ingested, errors } = await fetchAllSources()
    const clustered = await clusterNewItems()

    // Auto-generate for high-scoring new clusters
    const config = db.select().from(settings).where(eq(settings.id, 'singleton')).get()
    const threshold = config?.autoGenerateThreshold ?? 6.5
    const sixHoursAgo = Date.now() - 6 * 60 * 60 * 1000

    const autoGenCandidates = db.select()
      .from(eventClusters)
      .where(
        and(
          eq(eventClusters.status, 'new'),
          eq(eventClusters.postCount, 0),
          gt(eventClusters.firstSeenAt, sixHoursAgo)
        )
      )
      .all()
      .filter(c => (c.relevanceScore ?? 0) >= threshold)

    let autoGenerated = 0
    for (const cluster of autoGenCandidates) {
      try {
        const posts = await generateSmartPosts(cluster)
        if (posts.length > 0) autoGenerated++

        // Send to Lark if enabled
        if (config?.larkEnabled === 1 && process.env.LARK_APP_ID && process.env.LARK_REVIEW_CHAT_ID) {
          try {
            const { sendClusterToLark } = await import('@/lib/lark/messages')
            const { db: dbImport } = await import('@/lib/db')
            const { generatedPosts } = await import('@/lib/db/schema')
            const { eq: eqImport } = await import('drizzle-orm')
            const freshPosts = dbImport.select().from(generatedPosts)
              .where(eqImport(generatedPosts.clusterId, cluster.id)).all()
            const messageId = await sendClusterToLark(cluster, freshPosts)
            if (messageId) {
              for (const p of freshPosts) {
                dbImport.update(generatedPosts)
                  .set({ larkMessageId: messageId, larkSentAt: Date.now() })
                  .where(eqImport(generatedPosts.id, p.id))
                  .run()
              }
            }
          } catch (larkErr) {
            console.error('Lark send failed:', larkErr)
          }
        }
      } catch (e) {
        console.error('Auto-generate failed for cluster', cluster.id, e)
      }
    }

    return NextResponse.json({ ingested, clustered, errors, autoGenerated })
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
